### ISSUE TITLE
Bluetooth device detection.

### ISSUE THREAD

**Issue by michaelhickarus** [solocatz/XCMania#1]
I'm trying to pair a Skydrop BLE vario to the app and don't see it on the scanned list. Is it compatible? Am I missing a step?

**Comment by michaelhickarus** [comment]
Sorry... iOS, 14.4 Skydrop build 5205

**Comment by solocatz** [comment]
Thanks for your feedback. 

This bug should be fixed in 1.7.5, which would be out tomorrow.
Please let me know if it works or not.

**Comment by michaelhickarus** [comment]
Thank you, I will report.

**Comment by michaelhickarus** [comment]
Tested the pairing and it now recognizes and it now appears to detect and pair with the device.
